---
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00" # UTC
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00" # UTC
  - package-ecosystem: "bundler"
    directory: "src/opt/publisher"
    schedule:
      interval: "daily"
      time: "09:00" # UTC
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00" # UTC
