---
name: ♻️ OpenSSF Scorecard

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 6 * * 1"

permissions: {}

jobs:
  openssf-scorecard:
    name: OpenSSF Scorecard
    permissions:
      contents: read
      id-token: write
      security-events: write
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-openssf-scorecard.yml@f3b2ed398ec5c17e2f59d983bc01c79c73632246 # v7.3.0
