---
name: ♻️ Super Linter

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  super-linter:
    name: Super Linter
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-super-linter.yml@7c80b25e08b491427f45316a8c10ba44232d985f # v7.2.0
    with:
      super-linter-variables: |
        {
          "ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT": false,
          "VALIDATE_CSS": false,
          "VALIDATE_TRIVY": false
        }
