---
name: ♻️ Dependency Review

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  dependency-review:
    name: Dependency Review
    permissions:
      contents: read
      pull-requests: write
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-dependency-review.yml@7c80b25e08b491427f45316a8c10ba44232d985f # v7.2.0
