---
name: ♻️ Container Scan

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  container-scan:
    name: Container Scan
    permissions:
      contents: read
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-container-scan.yml@7c80b25e08b491427f45316a8c10ba44232d985f # v7.2.0
