---
name: ♻️ Super Linter

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  super-linter:
    name: Super Linter
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-super-linter.yml@f3b2ed398ec5c17e2f59d983bc01c79c73632246 # v7.3.0
    with:
      super-linter-variables: |
        {
          "ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT": false,
          "VALIDATE_CSS": false,
          "VALIDATE_TRIVY": false
        }
