---
name: ♻️ Container Test

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  container-test:
    name: Container Test
    permissions:
      contents: read
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-container-test.yml@f3b2ed398ec5c17e2f59d983bc01c79c73632246 # v7.3.0
