---
name: ♻️ Build and Test

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build
        id: build
        shell: bash
        run: |
          docker build --file Dockerfile --tag ministryofjustice/tech-docs-github-pages-publisher:latest .

      - name: Package
        id: package
        shell: bash
        run: |
          docker run --rm \
            --volume ${GITHUB_WORKSPACE}/test:/app \
            ministryofjustice/tech-docs-github-pages-publisher:latest /usr/local/bin/package

      - name: Lychee
        id: lychee
        uses: lycheeverse/lychee-action@c053181aa0c3d17606addfe97a9075a32723548a # v1.9.3
        with:
          args: --verbose --no-progress './**/*.md' './**/*.html' './**/*.erb' --accept 403,200,429
          fail: true
