name: Build and Publish Docker Image

on:
  workflow_dispatch:
  pull_request:
    branch: main
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Latest Image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build
        uses: docker/build-push-action@v4
        with:
          push: false

      - name: Login to DockerHub
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ministryofjustice/tech-docs-github-pages-publisher:latest

      - name: Report failure to Slack
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          notification_title: "Failed GitHub Action Run"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
